// app/blog/vibe-coding-website-bugs/page.tsx
// NOTE: if you don't have a /blog route yet, this file creates it —
// the page lives at getqalaunch.com/blog/vibe-coding-website-bugs

import type { Metadata } from 'next'
import Link from 'next/link'
import { SiteNav } from '@/components/site/site-nav'
import { SiteFooter } from '@/components/site/site-footer'

export const metadata: Metadata = {
  title: 'Vibe Coding Website Bugs: The 9 Problems Every AI-Built Site Ships With | QAlaunch',
  description: 'Built your website with vibe coding — Lovable, Bolt, Replit, v0, or Claude? These are the 9 frontend bugs almost every AI-built site ships with, and how to check for each one.',
  openGraph: {
    title: 'Vibe Coding Website Bugs: The 9 Problems Every AI-Built Site Ships With',
    description: 'The frontend bugs almost every vibe-coded website ships with, and how to check for each one before your users find them.',
    url: 'https://getqalaunch.com/blog/vibe-coding-website-bugs',
    type: 'article',
  },
}

const BUGS = [
  {
    n: '01',
    title: 'The form that works for you and nobody else',
    body: 'You test your contact form while logged into your builder, and it works. A real visitor submits it and nothing happens — no confirmation, no email, no database row. This is the single most common vibe coding bug because the builder preview environment differs from your deployed site: environment variables not copied to production, database permissions that only allow the owner to write, or success states that render without the submission actually succeeding. How to check: open your live site in an incognito window, submit the form with a test message, then go look in your actual database or inbox. Do not trust the success message.',
  },
  {
    n: '02',
    title: 'CTA text that vanishes on mobile',
    body: 'AI builders optimise for the preview pane you watch while prompting — a desktop-width view. Button text that contrasts fine on a wide layout can inherit different styles at mobile breakpoints and become invisible against its background. How to check: open your site on an actual phone (or DevTools at 375px width) and tap every button. Watch the text during the tap — hover and active states are where labels most often disappear.',
  },
  {
    n: '03',
    title: 'Navigation links that go nowhere',
    body: 'Client-side routing is where AI builders most often produce something that looks right and quietly fails. Sub-menu items, footer links, and "View all" buttons frequently point to routes that were renamed in a later prompt, or to "/" as a placeholder that never got updated. How to check: click every single navigation link on the live site — including every item inside dropdowns — and confirm the page actually changes to the right destination.',
  },
  {
    n: '04',
    title: 'The hero that eats the whole screen on mobile',
    body: 'A hero section sized for the desktop preview often renders at 150% or more of a phone\'s viewport height. Mobile visitors see a banner, and nothing else — no value proposition, no CTA — unless they scroll on faith. How to check: load your homepage on a phone. If you can\'t see any content or action button without scrolling, the hero needs to shrink at mobile breakpoints.',
  },
  {
    n: '05',
    title: 'Auth that only works because you were already logged in',
    body: 'Sign-up and login flows generated by AI tools routinely work in the builder — where you\'re already authenticated — and break for genuinely new users: broken redirect URLs on the live domain, email confirmations pointing at localhost, session logic that assumes an existing cookie. How to check: incognito window, brand-new email address, complete the entire signup on the live site, including clicking the confirmation email link.',
  },
  {
    n: '06',
    title: 'External links that hijack the visitor',
    body: 'Links to your LinkedIn, GitHub, or social profiles generated without target="_blank" navigate the visitor away from your site entirely. Each click on a credibility link becomes an exit. How to check: click every external link and confirm it opens in a new tab.',
  },
  {
    n: '07',
    title: 'The logo that goes nowhere',
    body: 'AI builders frequently render your logo as a plain image rather than a link to the homepage. It\'s the first thing lost visitors click. How to check: from any inner page, click your logo. If nothing happens, it needs to be wrapped in a link to "/".',
  },
  {
    n: '08',
    title: 'Safari: the browser your builder never showed you',
    body: 'Builder previews run on Chromium. Safari — which is every iPhone visitor — handles certain JavaScript events, date inputs, and CSS features differently. Drag-and-drop, custom pickers, and scroll effects that work perfectly in the preview can break completely on iOS. How to check: borrow an iPhone (or use a browser testing service) and walk through your key interactions.',
  },
  {
    n: '09',
    title: 'Missing page titles and descriptions',
    body: 'Meta titles and descriptions affect nothing visible on the page, so vibe coding workflows skip them constantly. The result: your site appears in Google as "Untitled" or with a random code snippet as its description. How to check: view page source and look for the <title> tag and meta description on every key page — or run an automated scan that checks all of them at once.',
  },
]

export default function VibeCodingBugsPost() {
  return (
    <>
      <SiteNav />
      <main className="bg-white min-h-screen pt-16">

      <article className="max-w-2xl mx-auto px-6 py-16">
        <div className="text-xs font-bold tracking-widest uppercase text-[#16a34a] mb-4">
          VIBE CODING · QA
        </div>
        <h1 className="text-3xl md:text-4xl font-extrabold leading-tight tracking-tight mb-5 text-[#09111f]">
          Vibe Coding Website Bugs: The 9 Problems Every AI-Built Site Ships With
        </h1>
        <p className="text-[#5b6472] text-lg leading-relaxed mb-4">
          Vibe coding — describing what you want and letting Lovable, Bolt.new, Replit, v0, or Claude
          build it — is the fastest way anyone has ever been able to ship a website. It is also the
          fastest way anyone has ever been able to ship bugs they don&apos;t know exist.
        </p>
        <p className="text-[#5b6472] text-lg leading-relaxed mb-4">
          The pattern is always the same: the site looks finished in the builder&apos;s preview, so it
          feels finished. But the preview is not a real browser, not a real phone, and not a real
          first-time visitor. Here are the nine bugs we see most often in AI-built websites — each with
          a way to check for it yourself in under a minute.
        </p>
        <p className="text-[#5b6472] text-lg leading-relaxed mb-10">
          Two of them cause so much damage that they&apos;ve earned full deep-dives:{' '}
          <Link href="/blog/contact-form-not-working" className="text-[#16a34a] font-semibold hover:underline">
            why contact forms fail silently
          </Link>{' '}
          and{' '}
          <Link href="/blog/website-looks-fine-on-desktop-broken-on-mobile" className="text-[#16a34a] font-semibold hover:underline">
            why sites look fine on desktop but break on mobile
          </Link>
          . Start there if either sounds familiar.
        </p>

        <div className="space-y-10">
          {BUGS.map((bug) => (
            <section key={bug.n}>
              <div className="flex items-baseline gap-3 mb-2">
                <span className="text-[#22c55e] font-extrabold text-xl">{bug.n}</span>
                <h2 className="text-xl font-bold text-[#09111f]">{bug.title}</h2>
              </div>
              <p className="text-[#3b4253] leading-relaxed">{bug.body}</p>
            </section>
          ))}
        </div>

        <div className="mt-14 bg-[#eef6f0] border border-[#d1e9d9] p-6">
          <h2 className="text-lg font-bold mb-2 text-[#09111f]">Check all nine automatically</h2>
          <p className="text-sm text-[#3b4253] mb-4 leading-relaxed">
            Every check above — plus about 26 more — is what{' '}
            <Link href="/" className="text-[#16a34a] font-semibold hover:underline">QAlaunch</Link>{' '}
            runs automatically. Paste your URL, and a real cloud browser opens your live site on desktop
            and mobile, runs the full checklist plus an AI visual review, and gives you your top issues
            in about 2 minutes. Free, no signup.
          </p>
          <p className="text-sm text-[#3b4253]">
            Building with a specific platform? See the dedicated guides:{' '}
            <Link href="/for-lovable" className="text-[#16a34a] font-semibold hover:underline">testing Lovable sites</Link>,{' '}
            <Link href="/for-bolt" className="text-[#16a34a] font-semibold hover:underline">testing Bolt.new sites</Link>,{' '}
            <Link href="/for-shopify" className="text-[#16a34a] font-semibold hover:underline">Shopify store audits</Link>, and{' '}
            <Link href="/for-wordpress" className="text-[#16a34a] font-semibold hover:underline">WordPress site checks</Link>.
          </p>
        </div>
      </article>

    </main>
      <SiteFooter />
    </>
  )
}
