onlyBuiltDependencies:
  - inngest-cli
ignoredBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
allowBuilds:
  esbuild: true
  inngest-cli: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
